AppBundle/Entity/Attachment.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\MappedSuperclass
 */
abstract class Attachment
{
    abstract public function getObject();

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="file", type="string", length=255, nullable=true)
     */
    private $file;

    private $uploadedFile;

    /**
     * @var int
     *
     * @ORM\Column(name="file_size", type="integer", nullable=true)
     */
    private $fileSize;

    /**
     * @var string
     *
     * @ORM\Column(name="file_extension", type="string", length=255, nullable=true)
     */
    private $fileExtension;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;

    /**
     * @return mixed
     */
    public function getUploadedFile()
    {
        return $this->uploadedFile;
    }

    public function getFileSizeKb()
    {
        return round($this->getFileSize()/1024, 2);
    }

    /**
     * @param mixed $uploadedFile
     * @return Attachment
     */
    public function setUploadedFile($uploadedFile)
    {
        $this->setUpdatedAt(new \DateTime('now'));
        $this->uploadedFile = $uploadedFile;
        return $this;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set file
     *
     * @param string $file
     *
     * @return $this
     */
    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * Get file
     *
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @return int
     */
    public function getFileSize()
    {
        return $this->fileSize;
    }

    /**
     * @param int $fileSize
     * @return Attachment
     */
    public function setFileSize($fileSize)
    {
        $this->fileSize = $fileSize;
        return $this;
    }

    /**
     * @return string
     */
    public function getFileExtension()
    {
        return $this->fileExtension;
    }

    /**
     * @param string $fileExtension
     * @return Attachment
     */
    public function setFileExtension($fileExtension)
    {
        $this->fileExtension = $fileExtension;
        return $this;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return $this
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function __toString()
    {
        return (string) $this->getName();
    }
}

AppBundle/Controller/Block/AttachmentController.php
<?php

namespace AppBundle\Controller\Block;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class AttachmentController extends Controller
{
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        return $this->render('AppBundle:Block:attachment.html.twig', [
            'attachments' => $em->getRepository('AppBundle:PageAttachment')->findBy(['object' => $this->get('cms.page')->getObject()])
        ]);
    }
}

AppBundle/Controller/Block/LeftMenuController.php
<?php

namespace AppBundle\Controller\Block;

use AppBundle\Menu\MenuCatalog;
use Intpill\CmsBundle\Entity\Page;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class LeftMenuController extends Controller
{
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $menuItems = null;
        $currentMenuItem = null;
        $page = $this->get('cms.page');
        $menuBuilder = $this->get('cms.menu.builder');
        if (($page->getType() == Page::TYPE_MODULE) && (in_array($page->getRoute(), ['catalog', 'product', 'product_tag', 'catalog_tags']))) {
            $menu = $menuBuilder->buildByClass(MenuCatalog::class);
            $menuItems = $menu->childrenByObject(null);
        } else {
            if (($currentMenuItems = $this->get('cms.page')->getObject()->getMenu()) && count($currentMenuItems)) {
                foreach ($currentMenuItems as $currentMenuItem) {
                    if (
                        ($parentMenu = $currentMenuItem->getParent()) &&
                        ($rootMenu = $parentMenu->getParent()) &&
                        ($rootMenu->getId() == $this->getParameter('main_menu_id'))
                    ) {
                        $menu = $menuBuilder->build();
                        $menuItems = $menu->childrenByObject($parentMenu);
                        break;
                    }
                }
            }
        }

        return $this->render('AppBundle:Block:left_menu.html.twig', [
            'menuItems' => $menuItems,
            'menuBuilder' => $menuBuilder
        ]);
    }
}

AppBundle/Controller/Block/MainMenuController.php
<?php

namespace AppBundle\Controller\Block;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class MainMenuController extends Controller
{
    public function indexAction(Request $request)
    {
        $mainMenu = $this->getDoctrine()->getRepository('CmsBundle:Menu')->find($this->getParameter('main_menu_id'));
        $menuBuilder = $this->get('cms.menu.builder');
        $menuItems = $menuBuilder->create($mainMenu);

        return $this->render('AppBundle:Block:main_menu.html.twig', [
            'menuItems' => $menuItems
        ]);
    }
}

AppBundle/Resources/views/Block/attachment.html.twig
{% if attachments %}
    <ul class="files" style="font-size:90%;line-height:1em;">
        {% for attachment in attachments %}
            <li class="{{ attachment.fileExtension }}">
                <a href="{{ asset(attachment_dir~attachment.file) }}" target="_blank">{{ attachment.name }}</a><br>
                <span class="small gray6">(Adobe&nbsp;Acrobat,&nbsp;{{ attachment.fileSizeKb }}&nbsp;Кб)</span>
            </li>
        {% endfor %}
    </ul>
    <p class="small">Для просмотра документов в формате PDF Вам может понадобится
        <noindex>
            <a href="http://www.adobe.com/products/acrobat/readstep2.html" target="_blank" rel="nofollow">Acrobat Reader</a>
        </noindex>.
    </p>
{% endif %}

AppBundle/Resources/views/Block/left_menu.html.twig
<nav class="span2 hidden-print ">
    {% if menuItems %}
        <ul class="nav page-nav-left">
            {% for menuItem in menuItems %}
                {% set menu = menuBuilder.build(menuItem) %}
                {% set menuChildren = menu.children(menuItem) %}
                {% set isActive = menuItem.active %}
                {% for menuChild in menuChildren %}
                    {% if menuChild.active %}
                        {% set isActive = true %}
                    {% endif %}
                {% endfor %}
                <li class="dropdown{% if menuItem.active %} selected{% endif %}{% if isActive %} select-parent{% endif %}">
                    <a href="{{ menuItem.url }}">{{ menuItem.name }}</a>
                    {% if menuChildren %}
                        <ul class="nav page-nav-left">
                            {% for menuChild in menuChildren %}
                                <li class="dropdown {% if menuChild.active %} selected select-parent{% endif %}"><a href="{{ menuChild.url }}">{{ menuChild.name }}</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</nav>

AppBundle/Resources/views/Block/main_menu.html.twig
<nav class="cs-navigation navbar navbar-default1">
    <div class="container">
        <div class="navbar-header">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed " data-toggle="collapse" data-target="#respons-menu" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="text-menu">Меню</span>
                </button>
                <ul class="cs-navigation__toggle-list list-unstyled hidden-md hidden-lg">
                    <li class="cs-navigation__toggle-item hidden-xs"><a href="tel:8-800-234-20-15" class="cs-navigation__toggle-link cs-navigation__toggle-phone--link"><img src="{{ asset('assets/img/toggl-phon.png') }}" alt="ico" class="cs-navigation__toggle-phone">8-800-234-20-15</a></li>
                    <li class="cs-navigation__toggle-item"><a rel="nofollow" href="/lk/" class="cs-navigation__toggle-login s-navigation__toggle-link"><img src="{{ asset('assets/img/nv-icon.png') }}" alt="ico"><span class="hidden-xs hidden-sm">&nbsp;Кабинет дистрибьютора</span></a></li>
                    <li class="cs-navigation__toggle-item hidden-sm hidden-md hidden-lg"><a href="tel:8-800-234-20-15" class="cs-navigation__toggle-link cs-navigation__toggle-phone--link"><img src="{{ asset('assets/img/toggl-phon.png') }}" alt="ico" class="cs-navigation__toggle-phone"></a></li>
                    <li class="cs-navigation__toggle-item"><a href="/search" class="cs-navigation__toggle-link"><img src="{{ asset('assets/img/search-icon.png') }}" alt="ico"></a></li>
                    <li class="cs-navigation__toggle-item"><a class="replace-email cs-navigation__toggle-link"><img src="{{ asset('assets/img/mail-icon.png') }}" alt="ico"></a></li>
                </ul>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="respons-menu">
            <ul class="cs-navigation__list nav navbar-nav">
                <li class="cs-navigation__item hidden-sm hidden-xs"><a href="/" class="cs-navigation__link"><img src="{{ asset('assets/img/home.png') }}" alt="ico"></a></li>
                {% for menuItem in menuItems %}
                    <li class="cs-navigation__item dropdown">
                        <a href="#" class="dropdown-toggle cs-navigation__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ menuItem.name }} <span class="caret"></span></a>
                        {% if menuItem.children %}
                            <ul class="dropdown-menu">
                                {% for menuChild in menuItem.children %}
                                    <li><a href="{{ menuChild.url }}">{{ menuChild.name }}</a></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <a href="/lk/" rel="nofollow" class="cs-navigation__login cs-navigation__link btn hidden-sm hidden-xs"><img class="hidden-sm hidden-xs" src="{{ asset('assets/img/nv-icon.png') }}" alt="ico">&nbsp;Кабинет дистрибьютора</a>
        </div>
    </div><!-- /.container -->
</nav>